#include <hyperion/platform/def.h>

HYPERION_IGNORE_UNUSED_MACROS_WARNING_START;

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN

HYPERION_IGNORE_UNUSED_MACROS_WARNING_STOP;

HYPERION_IGNORE_UNSAFE_BUFFER_WARNING_START;
#include <hyperion/platform/testing.h>
HYPERION_IGNORE_UNSAFE_BUFFER_WARNING_STOP;

#include <ostream>
